config/routes.rb
Rails.application.routes.draw do

  devise_for :users
resources :teams do
  resources :players, shallow: true
end

root "teams#index"

end

app/models/player.rb
class Player < ActiveRecord::Base
  
 belongs_to :team

end

app/models/team.rb
class Team < ActiveRecord::Base

 has_many :players, dependent: :destroy

 validates :name, presence: true, format: {with: /\A[a-zA-Z]+\z/, message: "Only Letters are allowed"}
 validates :division, presence: true, numericality: {greater_than_or_equal_to: 0}


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  attr_accessor :login #this method makes a getter and a setter

  validates :username, presence: true, length: {maximum: 255}, uniqueness: { case_sensitive: false }, format: { with: /\A[a-zA-Z0-9]*\z/, message: "may only contain letters and numbers." } #creates validators for the username 

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.find_first_by_auth_conditions(warden_conditions)
	conditions = warden_conditions.dup
    if login = conditions.delete(:login)
       where(conditions).where(["username = :value OR lower(email) = lo    wer(:value)", { :value => login }]).first
	else
       where(conditions).first
	end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  protect_from_forgery with: :exception
 


end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

#before_action :authenticate_user!, :set_player, only: [:new, :edit, :update, :destroy] ***Note: had errors with ":set_player" but worked when took it out
before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]



def index
 @team = Team.find(params[:team_id])
 
 @players = @team.players
end

def new
 @team = Team.find(params[:team_id])
 
 @player = @team.players.new
end

def create
 @team = Team.find(params[:team_id])
 @player = @team.players.new(player_params)

 if @player.save
   redirect_to team_players_url(@team), notice: 'Player was succesfully created!'
 else
   render :new
 end
end

def edit
end

def update
  if @player.update(player_params)
    redirect_to team_players_url(@player.team), notice: 'Player was succesfully updated!'
  else
    render :edit
  end
end

def destroy
  @player.destroy
  redirect_to team_players_url(@player.team), notice: "Player was deleted!"
end


private

 def set_player
   @player = Player.find(params[:id])
 end

 def player_params
   params.require(:player).permit(:first, :last, :hits, :assists)
 end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

 before_action :authenticate_user!, only: [:new, :create, :edit, :destroy]
 #GET /teams
 def index
  @teams = Team.all
 end

 def show
  @team = Team.find(params[:id])
 end

 def new
  @team = Team.new
 end

 def create
  @team = Team.new(params.require(:team).permit(:name, :division))
  if @team.save
   redirect_to @team, notice: "Team has succesfully been added!"
  else
   render :new
  end
 end

 def edit
  @team = Team.find(params[:id])
 end

 def update
  @team = Team.find(params[:id])
  if @team.update(params.require(:team).permit(:name, :division))
    redirect_to @team, notice: "Team has been succesfully updated!"
  else
   render :edit
  end
 end

 def destroy
  @team = Team.find(params[:id])
  @team.destroy
   redirect_to teams_url
 end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Llstats</title>
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css">
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Big League Coders</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/teams">Teams</a></li>
      </ul>
<!--lines 28 to 36 add appropriate links or notice about the user being logged in in the top right corner of the navigation bar-->
	  <p class="navbar-text pull-right">
	  <% if user_signed_in? %>
	  Logged in as <strong><%= current_user.email %></strong>.
	  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
	  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
	  <% else %>
	  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
	  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
	  <% end %>
	  </div>
  </div>
</nav>

<div class="container">
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <%= yield %>
</div>


<footer>
  <div class="container">
    Big League Coders. 
  </div>
</footer>
<script src="//railsgirls.com/assets/bootstrap.js"></script>

</body>
</html>

app/views/players/_player_form.html.erb
<%= form_for([@team, @player]) do |player| %>
 <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this Player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message  %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= player.label :last %><br>
    <%= player.text_field :last %>
  </div>
  <div class="field">
    <%= player.label :first %><br>
    <%= player.text_field :first %>
  </div>
  <div class="field">
    <%= player.label :hits %><br>
    <%= player.text_field :hits %>
  </div>
  <div class="field">
    <%= player.label :assists %><br>
    <%= player.text_field :assists %>
  </div>
  <div class="actions">
    <%= player.submit %>
  </div>

<% end %>

app/views/players/edit.html.erb
<h1> Edit player from <%= @player.team.name %> </h1>
<br>
<hr>

<%= render "player_form" %>

<%= link_to "Back", team_players_path(@player.team) %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1> Player Roster for Team: <%= @team.name %> </h1>
<br>
<hr>

<table>
  <thead>
    <tr>
       <th> Last_Name </th>
       <th> First_Name </th>
       <th> Hits (H) </th>
       <th> Assists (A) </th>
       <th colspan="4" > </th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |cur_player| %>
      <tr>
        <td> <%= cur_player.last %> </td>
        <td> <%= cur_player.first %> </td>
        <td> <%= cur_player.hits %> </td>
        <td> <%= cur_player.assists %> </td>
        <td> <%= link_to "Edit", edit_player_path(cur_player) %> </td>
        <td> <%= link_to "Delete", cur_player, method: :delete, data: { confirm: "Are you sure?" } %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "Add Player", new_team_player_path %> |
<%= link_to "Back to #{@team.name}'s Homepage", team_path(@team) %>

app/views/players/new.html.erb
<h1> Add a new player to <%= @team.name %>'s Roster </h1>
<br>
<hr>

<%= render "player_form" %>

<%= link_to "Back", team_players_path %>